GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJuYW1lIjoiWW9zc2kgTm9yZGlhbnNhaCIsImVtYWlsIjoieW9zc2kubm9yZGlhbnNhaDk5QGdtYWlsLmNvbSIsImlhdCI6MTczNDUzMjEwNiwiZXhwIjoxNzM0NTMyMTI2fQ.v8KRrSK91aP0NIFEbZUwqzBFILviVzvlr_rWsO3doek

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "Yossi Nordiansah",
    "password": "yossi234",
    "confPassword": "yossi234",
    "nama": "Yossi Nordiansah",
    "nim": "52104110023",
    "email": "yossi.nordiansah99@gmail.com",
    "prodi": "Teknik Informatika",
    "semester": "7",
    "nomor_telepon": "085655230897"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "yossi.nordiansah99@gmail.com",
    "password": "yossi234"
}

###
GET http://localhost:3000/users/token

###
DELETE http://localhost:3000/users/logout

